# -*- coding: utf-8 -*-
"""Image names in pickle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13NkyHTXrMS4dXGziyG7qz_AIThpm4idf
"""

!pip3 install pydicom

from pydicom.data import get_testdata_files
import pydicom
import os
import numpy as np
from google.colab import drive

path = 'drive/My Drive/Capstone/stage_2_train_images/'

drive.mount('/content/drive') #mouting drive

os.chdir(path) #changing the current directory path to the project direcotry where the dataset is available
path = os.getcwd() # directory path of all the images

# List of all the images
images = os.listdir()

import pickle
with open('../ImageNames.pkl','wb') as image_names:
    pickle.dump(images,image_names)



